camera_settings:
  mode: 'manual'  # manual or auto
  resolution: [1920, 1080]
  framerate: 30
  shutter_speed: 10000  # in microseconds
  exposure_time: 10000  # in microseconds
  brightness: 50
  contrast: 0
  saturation: 0
  awb_mode: 'auto'  # auto white balance mode
  iso: 100
  color_space: 'sRGB'  # Possible values: 'sRGB', 'AdobeRGB', 'Rec2020', etc.