config:
  transform:                # Image transformation (identity, hflip, vflip, hvflip)
    hflip: false
    vflip: true
  colour_space: Sycc()      # Colour space (sYCC, SMPTE170M, Rec709)
  buffer_count: 4           # Number of buffer sets
  queue: false              # Queue up a frame ready for capture

  main:
    size: [1440, 1080]
    format: 'BGR888'

  controls:
    ExposureTime: 10000        # Exposure time in microseconds
    # FrameDurationLimits: (33333, 33333) 
    AnalogueGain: 1.0         # Gain multiplier
    Brightness: 0.0           # Brightness adjustment
    Contrast: 1.0             # Contrast adjustment
    Saturation: 1.0           # Saturation adjustment
    # Sharpness: 1.0            # Sharpness adjustment
    # AeMeteringMode: "centre-weighted"  # Auto exposure metering mode
    # AeExposureMode: "auto"    # Auto exposure mode
    # AwbMode: "auto"           # Auto white balance mode
    # AwbEnable: true           # Enable auto white balance
    # FocusMode: "auto"         # Focus mode
    # AfTrigger: false          # Autofocus trigger
    # LensPosition: 0.0         # Manual lens position
    # NoiseReductionMode: "high-quality" # Noise reduction mode
    # StillsPostProcessing: "normal"  # Post-processing mode for stills capture

